<?php

/**
 * Implementation of hook_menu
 */
function rbkc_fso_menu() {
  
  $items = array();
  
  $items['user/directlogin'] = array(
    'title' => 'FLI',
    'page callback' => 'rbkc_fso_login',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['user/directlogout'] = array(
    'title' => 'FLO',
    'page callback' => 'rbkc_fso_logout',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Handler for menu item /user/fso/%
 * @param string $username The username parameter
 * @return array|mixed|string
 */
function rbkc_fso_login() {
  global $user;
  
  if ($user->uid) {
    return 'You must be logged out first';
  }
  
  return drupal_get_form('rbkc_fso_form');
}

/**
 * Handler for /user/flo
 */
function rbkc_fso_logout() {
  module_load_include('pages.inc', 'user');
  user_logout();
}

function rbkc_fso_form($form, &$form_state, $username) {
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => $username,
    '#size' => 50,
    '#required' => true,
  );
  
  $form['pass'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
    '#size' => 50,
    '#required' => true,
  );
 
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Go'),
  );
  
  return $form;
}

function rbkc_fso_form_submit($form, &$form_state) {
  global $user;

  $account = user_load_by_name($form_state['values']['name']);
  if ($account) {
    if (user_access('administer users', $account)) {
      if (user_authenticate($form_state['values']['name'], $form_state['values']['pass'])) {
        $user = $account;
        $form_state['redirect'] = 'admin/people';
        user_login_finalize($form_state);
      }
      else {
        drupal_set_message('Wrong username or password', 'error');
      }
    }
    else {
      drupal_set_message('Not allowed for this username', 'warning');
    }
  }
  else {
    drupal_set_message('Wrong username or password', 'error');
  }
}